name: Update GitHub Stats

on:
  schedule:
    - cron: '0 */8 * * *'
  push:
    branches:
      - main

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub

    - name: Run stats update script
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: python script.py

    - name: Commit files and push changes
        run: |-
          git add .
          git diff
          git config --global user.email "github-actions-bot@andrew6rant.github.io"
          git config --global user.name "Andrew6rant/GitHub-Actions-Bot"
          git commit -m "Updated README" -a || echo "No changes to commit"
          git push
